const List<String> interestList = [
  "Daily Life",
  "Comedy",
  "Entertainment",
  "Animals",
  "Food",
  "Beauty & Style",
  "Drama",
  "Learning",
  "Talent",
  "Sports",
  "Auto",
  "Family",
  "Fitness & Health",
  "DIY & Life Hacks",
  "Arts & Crafts",
  "Dance",
  "Outdoors",
  "Oddly Satisfying",
  "Home & Garden",
];

List<String> musicGenres = [
  'Rock',
  'Pop',
  'Hip Hop / Rap',
  'Jazz',
  'EDM',
  'R&B',
  'Country',
  'Classical',
  'Reggae',
  'Blues',
  'Metal',
  'Folk',
  'Soul',
  'Funk',
  'Alternative Rock',
  'House',
  'Techno',
  'Punk Rock',
  'Synth-Pop',
  'Ambient',
];

List<String> entertainmentGenres = [
  'Action',
  'Comedy',
  'Drama',
  'Science Fiction (Sci-Fi)',
  'Fantasy',
  'Horror',
  'Thriller',
  'Romance',
  'Mystery',
  'Documentary',
  'Animation',
  'Adventure',
  'Musical',
  'Crime',
  'Reality TV',
  'Game Show',
  'Stand-up Comedy',
  'Role-Playing Game (RPG)',
  'Strategy',
  'Sports',
];
